### PR TITLE
Add Tutorial Scene that demonstrates mechanics for player one at a time

### PR DESCRIPTION
**Pull request by SaamIAm**
Added TutorialFinal scene includes simply map for player to get used to control

Needs control description to explain controls to first time player.
Thinking about adding win condition to advance player to Level1 on win

Estimated: 90 Min: 60 Max: 120 Actual: 90

### CODE REVIEW

**Comment by SaamIAm** [comment]
Win trigger level advancement
Tutorial -> Level1
Level1   -> Level2
Level2   -> SwingUp

Tried to add a waitForSeconds(seconds) but could not get it to work.
Ideally I would like the pop up to say "You Win" -> wait(3) -> ChangeScene.

**Comment by Chris-Johnston** [comment]
image

Keep non-scene files out of the Scene folder. They don't go there.

**Comment by Chris-Johnston** [comment]
> I agree but also disagree I think they want to be challenged in the tutorial that shows the player what is at stake in the actual game. And trust me I made the game easier than I could have.

I think that challenge is fine, but only once the player has an understanding of how the game works. Otherwise that might make things frustrating.

Also, what happened to the idea of including controls in the level? Introducing the player to the controls is a must.

**Comment by SaamIAm** [comment]
I was having trouble adding the controls to the level. 
Discord: "Hey Chris I'm kind of confused on how to put text up in locations in the level without it being in the same spot no matter where I go like the Exit and Reset button
Also if I did put text down for tutorial instructions wouldn't the camera change mess it up if the player decides to cahnge the camera
Does someone want to add text that explains the controls in my tutorial level?
"

**Comment by Chris-Johnston** [comment]
Take a look how it was done in the closed tutorial branch.

**Comment by Chris-Johnston** [comment]
Still would like to have controls as floating text, but will be addressed later.

**Pull request merged**
