### PR TITLE
Level 1 and Tutorial Design Cleanup

### PR DESCRIPTION
**Pull request by SaamIAm**
Added boundary to tutorial incase player escapes wall.
Fixed Camera zoom in level1 to no longer show unintentional left side boundary lava

Estimated: 10 Min: 10 Max: 20 Actual: 10

### CODE REVIEW

**Comment by SaamIAm** [comment]
Can I merge?

**Comment by Chris-Johnston** [comment]
image
can possibly go out of bounds here

**Comment by Chris-Johnston** [comment]
Looks fine in the web player size, not sure how it'll look in the standalone. Having a bit of a 'safe zone' margin is nice to have.

**Comment by Chris-Johnston** [comment]
Also, RE: the margin thing, once we get a moving camera working this shouldn't be an issue.

**Pull request merged**
