### PR TITLE
Music/SFX/Control Icons

### PR DESCRIPTION
**Pull request by akehn24**
Music added to each playable level, sfx for player jump/land/grapple, and player control icons added.

Woohoo! No more documentation!! 

**ESTIMATED:** LIKE 100 HOURS **ACTUAL:** 400 DAYS

### CODE REVIEW

**Comment by akehn24** [comment]
image

**Comment by Chris-Johnston** [comment]
wait we don't have any more sprint reports to track anymore? No more keeping track of time all the time!?

**Comment by Chris-Johnston** [comment]
also shouldn't you be focused on the hackathon?

**Comment by akehn24** [comment]
Nah more Sprants bruh!! Also.......Snack Overflow isn't really rockin' right now, lawl.

**Comment by SaamIAm** [comment]
Getting this error.

NullReferenceException: Object reference not set to an instance of an object
PlayerCamera.LateUpdate () (at Assets/Scripts/PlayerCamera.cs:65)

**Comment by SaamIAm** [comment]
Also it would be nice to have a burning noice when the player hits lava.

**Pull request merged**
