### PR TITLE
Added skeleton Level2 bouncy theme

### PR DESCRIPTION
**Pull request by SaamIAm**
Added bouncy platforms to the level.
Level2 is about mixing more evenly grappling and movement features to add some variety to gameplay.
BUG: When I reset the level or die the lighting changes from the original? any ideas?

Estimated: 60 Min: 60 Max: 90  Actual: NA

### CODE REVIEW

**Comment by SaamIAm** [comment]
Let me know if you know why the colors go dark after RESET/Death

**Comment by Chris-Johnston** [comment]
That's because the level is being reloaded.
https://answers.unity.com/questions/919940/applicationloadlevel-changes-lighting-for-some-rea.html
See answers like this

**Comment by SaamIAm** [comment]
I updated to the current version of Unity so check out my branch and let me know if anything broke because of it? Now may be a good time for everyone to get the current Unity version.

I also fixed the lighting issue in Level2... but am still not sure why it occurred only in Level2 and not Level1 as they are using the same lighting system.

**Comment by Chris-Johnston** [comment]
image

**Comment by Chris-Johnston** [comment]
Also, I think that this level is a bit too "generic 2d platformer" and not enough "grapple hook" themed.

**Comment by SaamIAm** [comment]
The player explores the level, a level that can not be done without his trusty grappel

**Pull request merged**
