### PR TITLE
Added Exit button to scenes

### PR DESCRIPTION
**Pull request by SaamIAm**
Estimated: 20 Min: 10 Max: 20 Actual: 10

### CODE REVIEW

**Comment by SaamIAm** [comment]
I was having trouble making it into a prefab. Can you copy multiple game objects objects into one prefab?

**Comment by Chris-Johnston** [comment]
You can copy a single game object (and it's components and child game objects) into a prefab. You could also copy them into a multiple prefabs, or make an empty game object to contain all of the elements you need.

Then all you do is drag the object into the files window.

**Comment by SaamIAm** [comment]
Awsome, will do.

**Comment by SaamIAm** [comment]
Prefabs have been added

**Pull request merged**
